# test_initial_state.py

import pytest
import os

LOGS_DIR = "/home/user/logs"
LOG_FILE = "/home/user/logs/dashboard_events.log"
OUTPUT_FILE = "/home/user/logs/unique_services.txt"

DASHBOARD_EVENTS_LOG_CONTENT = """[2024-05-01T12:00:00Z] SERVICE=api EVENT=restarted
[2024-05-01T12:01:00Z] SERVICE=db EVENT=healthy
[2024-05-01T12:02:00Z] SERVICE=api EVENT=scaling
[2024-05-01T12:03:00Z] SERVICE=frontend EVENT=deployed
[2024-05-01T12:04:00Z] SERVICE=db EVENT=backup
"""

def test_logs_directory_exists():
    assert os.path.isdir(LOGS_DIR), (
        f"Required directory '{LOGS_DIR}' does not exist. "
        "Create it before proceeding."
    )

def test_dashboard_events_log_exists():
    assert os.path.isfile(LOG_FILE), (
        f"Required log file '{LOG_FILE}' does not exist. "
        "You must have this file before running the extraction."
    )

def test_dashboard_events_log_content():
    assert os.path.isfile(LOG_FILE), f"Log file '{LOG_FILE}' is missing."
    with open(LOG_FILE, "r", encoding="utf-8") as f:
        actual = f.read()
    expected = DASHBOARD_EVENTS_LOG_CONTENT
    actual_lines = [line.rstrip() for line in actual.splitlines()]
    expected_lines = [line.rstrip() for line in expected.splitlines()]
    assert (
        actual_lines == expected_lines
    ), (
        f"Log file '{LOG_FILE}' does not contain the expected log lines. "
        "Make sure it matches exactly (including order and number of lines):\n"
        + "\n".join(expected_lines)
    )

def test_unique_services_output_does_not_exist():
    assert not os.path.exists(OUTPUT_FILE), (
        f"Output file '{OUTPUT_FILE}' already exists. "
        "Remove it before running your extraction command; it will be generated by your command."
    )