# test_initial_state.py

import os
import pwd
import pytest

HOME = '/home/user'
API_CODE_DIR = os.path.join(HOME, 'old_api_code')
TEST_SCRIPT = os.path.join(API_CODE_DIR, 'test_api.py')
OUTPUT_LOG = os.path.join(HOME, 'api_test_output.log')

def test_old_api_code_directory_exists():
    assert os.path.isdir(API_CODE_DIR), (
        f"Required directory '{API_CODE_DIR}' does not exist. "
        "Please ensure the old_api_code directory exists in /home/user."
    )

def test_test_api_script_exists():
    assert os.path.isfile(TEST_SCRIPT), (
        f"Required script '{TEST_SCRIPT}' does not exist. "
        "Please ensure test_api.py is present at the specified location."
    )

def test_test_api_script_contents():
    expected = "print(\"API test successful. All endpoints returned 200 OK.\")\n"
    try:
        with open(TEST_SCRIPT, 'r', encoding='utf-8') as f:
            contents = f.read()
    except Exception as e:
        pytest.fail(
            f"Could not open '{TEST_SCRIPT}': {e}"
        )
    assert contents == expected, (
        f"Contents of '{TEST_SCRIPT}' do not match the expected script.\n"
        f"Expected:\n{expected!r}\nFound:\n{contents!r}"
    )

def test_output_log_does_not_exist():
    assert not os.path.exists(OUTPUT_LOG), (
        f"The output log '{OUTPUT_LOG}' already exists.\n"
        "Please remove this file before running the task, as the test expects it to be generated by your script."
    )